Repository dev-sec/puppet-os-hardening, pull requests merged in 2019-02, with the labels that each got.

#182 Add version tag on puppetforge
  README.md
Labels: enhancement, in progress

#183 Replace sysctl module
  .fixtures.yml
  README.md
  metadata.json
  test/fixtures/Puppetfile
Labels: enhancement, in progress

#184 Add missing dependency
  manifests/pam.pp
Labels: bug

#185 Replace Gitter with mailing lists
  README.md
Labels: in progress

#186 Update Mailing lists
  README.md
Labels: in progress, no changelog

#188 Readme updates
  README.md
Labels: enhancement, in progress

#189 New release 2.2.2
  CHANGELOG.md
  metadata.json
Labels: in progress, no changelog

#190 Update to PDK 1.9.0
  .puppet-lint.rc
  metadata.json
  spec/spec_helper.rb
Labels: enhancement, in progress
