Repository dev-sec/puppet-os-hardening, pull requests merged in 2021-02, with the labels that each got.

#259 use new syntax for stub in rspec
  .travis.yml
  kitchen.do.yml
  kitchen.yml
  lib/facter/home_users.rb
  lib/facter/retrieve_system_users.rb
  metadata.json
  spec/facter/home_users_spec.rb
  spec/facter/retrieve_system_users_spec.rb
  spec/fixtures/etc/login.defs
  spec/unit/facter/home_users_spec.rb
  spec/unit/facter/retrieve_system_users_spec.rb
Labels: enhancement

#262 Added manage_system_users option and formatted properties
  README.md
  manifests/init.pp
  manifests/minimize_access.pp
Labels: enhancement

#263 fixed alignment of properties and indentation
  manifests/login_defs.pp
Labels: enhancement

#264 move to github actions
  .github/workflows/tests.yml
  .sync.yml
  .travis.yml
  README.md
Labels: enhancement

#238 Move from inspec to cinc
  .github/workflows/tests.yml
  .sync.yml
  Gemfile
Labels: enhancement

#265 add source for chef-utils gem (bundle confusion)
  .sync.yml
  Gemfile
Labels: bug

#266 New release 2.3.0
  CHANGELOG.md
  metadata.json
  test/fixtures/metadata.json
Labels: no changelog

#268 Solve bundle problem on automated tests
  .sync.yml
  Gemfile
Labels: bug

#269 Activate manage_cron_permissions to satisfy cron tests
  test/fixtures/manifests.do/site.pp
  test/fixtures/manifests/site.pp
Labels: bug
