Repository dev-sec/puppet-os-hardening, pull requests merged in 2021-07, with the labels that each got.

#278 update to PDK template 2.1.1
  .gitignore
  .pdkignore
  Gemfile
  metadata.json
  spec/spec_helper.rb
Labels: enhancement

#281 Remove Puppet v5 support + tests
  .github/workflows/tests.yml
  kitchen.do.yml
  kitchen.yml
  metadata.json
Labels: enhancement

#282 Add Puppet 7 tests + new versions
  .github/workflows/tests.yml
  kitchen.do.yml
  kitchen.yml
  metadata.json
  test/fixtures/metadata.json
Labels: enhancement

#283 New release 2.3.1
  .sync.yml
  CHANGELOG.md
  Gemfile
  Rakefile
  metadata.json
  test/fixtures/metadata.json
Labels: no changelog

#285 Backwards incompatible breaking change in PR279 (#284)
  manifests/minimize_access.pp
Labels: bug

#286 New release 2.3.2
  CHANGELOG.md
  metadata.json
  test/fixtures/metadata.json
Labels: no changelog
